name: Node.js CI with Vite Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
    steps:
      # Step 1: Checkout code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js with caching for npm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies using npm
      - run: npm ci

      # Step 4: Build the project using Vite
      - run: npm run build  # Vite will create build files in 'dist' folder

      # Step 5: Deploy the build to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          folder: ./dist  # Vite's output folder
